name: Publish Python Package

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

jobs:
  publish:
    uses: ivanildobarauna/github-workflows/.github/workflows/publish-python-package.yml@v1
    with:
      python-version: "3.9"
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
