name: Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ivanildobarauna/github-workflows/.github/workflows/tests-python-poetry.yml@v1
    with:
      python-versions: '["3.9"]'
      environment: Development
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
